// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: Proto/message.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlanetaryServiceClient is the client API for PlanetaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlanetaryServiceClient interface {
	Add(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
	Rename(ctx context.Context, in *RenameMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
	Update(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
	Delete(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
}

type planetaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlanetaryServiceClient(cc grpc.ClientConnInterface) PlanetaryServiceClient {
	return &planetaryServiceClient{cc}
}

func (c *planetaryServiceClient) Add(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, "/grpc.PlanetaryService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planetaryServiceClient) Rename(ctx context.Context, in *RenameMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, "/grpc.PlanetaryService/Rename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planetaryServiceClient) Update(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, "/grpc.PlanetaryService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *planetaryServiceClient) Delete(ctx context.Context, in *BaseMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, "/grpc.PlanetaryService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlanetaryServiceServer is the server API for PlanetaryService service.
// All implementations must embed UnimplementedPlanetaryServiceServer
// for forward compatibility
type PlanetaryServiceServer interface {
	Add(context.Context, *BaseMessage) (*ReplyMessage, error)
	Rename(context.Context, *RenameMessage) (*ReplyMessage, error)
	Update(context.Context, *BaseMessage) (*ReplyMessage, error)
	Delete(context.Context, *BaseMessage) (*ReplyMessage, error)
	mustEmbedUnimplementedPlanetaryServiceServer()
}

// UnimplementedPlanetaryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlanetaryServiceServer struct {
}

func (UnimplementedPlanetaryServiceServer) Add(context.Context, *BaseMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedPlanetaryServiceServer) Rename(context.Context, *RenameMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedPlanetaryServiceServer) Update(context.Context, *BaseMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPlanetaryServiceServer) Delete(context.Context, *BaseMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPlanetaryServiceServer) mustEmbedUnimplementedPlanetaryServiceServer() {}

// UnsafePlanetaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlanetaryServiceServer will
// result in compilation errors.
type UnsafePlanetaryServiceServer interface {
	mustEmbedUnimplementedPlanetaryServiceServer()
}

func RegisterPlanetaryServiceServer(s grpc.ServiceRegistrar, srv PlanetaryServiceServer) {
	s.RegisterService(&PlanetaryService_ServiceDesc, srv)
}

func _PlanetaryService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetaryServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PlanetaryService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetaryServiceServer).Add(ctx, req.(*BaseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanetaryService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetaryServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PlanetaryService/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetaryServiceServer).Rename(ctx, req.(*RenameMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanetaryService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetaryServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PlanetaryService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetaryServiceServer).Update(ctx, req.(*BaseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlanetaryService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlanetaryServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.PlanetaryService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlanetaryServiceServer).Delete(ctx, req.(*BaseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PlanetaryService_ServiceDesc is the grpc.ServiceDesc for PlanetaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlanetaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.PlanetaryService",
	HandlerType: (*PlanetaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _PlanetaryService_Add_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _PlanetaryService_Rename_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PlanetaryService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PlanetaryService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto/message.proto",
}

// GetServiceClient is the client API for GetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetServiceClient interface {
	Get(ctx context.Context, in *QueryMessage, opts ...grpc.CallOption) (*ReplyMessage, error)
}

type getServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetServiceClient(cc grpc.ClientConnInterface) GetServiceClient {
	return &getServiceClient{cc}
}

func (c *getServiceClient) Get(ctx context.Context, in *QueryMessage, opts ...grpc.CallOption) (*ReplyMessage, error) {
	out := new(ReplyMessage)
	err := c.cc.Invoke(ctx, "/grpc.GetService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetServiceServer is the server API for GetService service.
// All implementations must embed UnimplementedGetServiceServer
// for forward compatibility
type GetServiceServer interface {
	Get(context.Context, *QueryMessage) (*ReplyMessage, error)
	mustEmbedUnimplementedGetServiceServer()
}

// UnimplementedGetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGetServiceServer struct {
}

func (UnimplementedGetServiceServer) Get(context.Context, *QueryMessage) (*ReplyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGetServiceServer) mustEmbedUnimplementedGetServiceServer() {}

// UnsafeGetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetServiceServer will
// result in compilation errors.
type UnsafeGetServiceServer interface {
	mustEmbedUnimplementedGetServiceServer()
}

func RegisterGetServiceServer(s grpc.ServiceRegistrar, srv GetServiceServer) {
	s.RegisterService(&GetService_ServiceDesc, srv)
}

func _GetService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.GetService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetServiceServer).Get(ctx, req.(*QueryMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// GetService_ServiceDesc is the grpc.ServiceDesc for GetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.GetService",
	HandlerType: (*GetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _GetService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto/message.proto",
}
